# Generated by Django 2.2 on 2019-12-02 20:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'Still playing'), ('draw', 'Finished as a draw'), ('x', 'Player X won'), ('o', 'Player O won')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=140)),
                ('x_player', models.CharField(max_length=140)),
                ('o_player', models.CharField(max_length=140)),
                ('board', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
