# Generated by Django 2.2 on 2019-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='finished',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Still playing'), ('draw', 'Finished as a draw'), ('x', 'Player X won'), ('o', 'Player O won')], default='in_progress', max_length=32),
        ),
    ]
